const {chromium}=require('playwright');
const fs=require('fs');const path=require('path');
(async()=>{
 fs.mkdirSync(path.resolve(__dirname,'results'),{recursive:true});
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const cats=[{id:1,name:'West Asia',slug:'west-asia',count:12},{id:2,name:'Video',slug:'video',count:2},{id:3,name:'Podcast',slug:'podcast',count:1},{id:4,name:'Art',slug:'art',count:1}];
 const tags=[{id:9,name:'Analysis',slug:'analysis',count:2},{id:10,name:'Videos',slug:'videos',count:1}];
 const authors=[{id:1,name:'Test Author'}];
 const make=(id,cat)=>({id,title:{rendered:cat===2?'A closer look: the video briefing':cat===3?'Conversations that matter':'Understanding the stories shaping our world'},date:'2026-09-29T12:00:00',date_gmt:'2026-09-29T07:00:00',link:'https://creedtimes.com/test-'+id,author:1,categories:[cat],tags:[9],content:{rendered:'<p>Test fixture for interface verification. This is not a published Creed Times story.</p><p>A thoughtful perspective on the news, with context that makes a difference.</p><img src=x onerror="window.PWNED=true"><script>window.PWNED=true</script><iframe src="https://example.com"></iframe>'+(cat===3?'<audio src="https://creedtimes.com/sample.mp3"></audio>':'')},_embedded:{author:authors,'wp:term':[[{...cats.find(c=>c.id===cat),taxonomy:'category'}],[{...tags[0],taxonomy:'post_tag'}]]}});
 const posts=[make(1,1),make(2,2),make(3,3),make(4,4)];let offline=false,requests=[];
 await page.route('https://creedtimes.com/**',async route=>{const u=new URL(route.request().url());requests.push(u.href);if(offline)return route.abort();let data=[];if(u.pathname.endsWith('/categories'))data=cats;else if(u.pathname.endsWith('/tags'))data=tags;else if(u.pathname.endsWith('/users'))data=authors;else if(u.pathname.endsWith('/posts')){data=posts;const category=u.searchParams.get('categories');if(category)data=data.filter(x=>category.split(',').includes(String(x.categories[0])));const excluded=u.searchParams.get('categories_exclude');if(excluded)data=data.filter(x=>!excluded.split(',').includes(String(x.categories[0])));if(u.searchParams.get('search'))data=data.filter(x=>x.id===1);}await route.fulfill({json:data,headers:{'Access-Control-Allow-Origin':'*'}});});
 const root=path.resolve(__dirname,'../app/src/main/assets');
 await page.route('https://app.creedtimes.local/**',route=>{let p=new URL(route.request().url()).pathname.slice(1);if(!fs.existsSync(path.join(root,p)))return route.abort();return route.fulfill({path:path.join(root,p),contentType:p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':p.endsWith('.png')?'image/png':'text/html'});});
 await page.goto('https://app.creedtimes.local/index.html');await page.locator('[data-post="1"]').waitFor();
 await page.screenshot({path:path.resolve(__dirname,'results/home.png'),fullPage:true});
 await page.click('[data-tab="articles"]');await page.locator('[data-post="1"]').waitFor();if(await page.locator('[data-post="2"]').count())throw Error('Articles contains media');
 await page.click('[data-tab="artworks"]');await page.locator('.art-card[data-post="4"]').waitFor();await page.screenshot({path:path.resolve(__dirname,'results/artworks.png'),fullPage:true});
 await page.click('[data-tab="all"]');await page.locator('[data-post="1"]').waitFor();
 await page.click('[data-post="1"]');await page.click('[data-action="save"]');await page.click('[data-action="favorite"]');
 if(await page.evaluate(()=>window.PWNED))throw Error('Content sanitization failed');
 if(await page.locator('.article iframe,.article script,.article [onerror]').count())throw Error('Unsafe content retained');
 await page.click('[data-action="back"]');await page.click('[data-nav="saved"]');await page.locator('[data-post="1"]').waitFor();
 await page.click('[data-library="favorites"]');await page.locator('[data-post="1"]').waitFor();
 await page.click('[data-nav="settings"]');await page.selectOption('[data-pref="theme"]','dark');
 if(!(await page.locator('body').getAttribute('class')).includes('dark'))throw Error('Dark mode failed');
 await page.screenshot({path:path.resolve(__dirname,'results/dark-settings.png'),fullPage:true});
 await page.click('[data-nav="home"]');await page.click('[data-tab="video"]');await page.locator('[data-post="2"]').waitFor();if(await page.locator('[data-post="1"]').count())throw Error('Video filtering failed');
 if(!requests.some(u=>u.includes('tax_relation=OR')))throw Error('Media OR taxonomy missing');
 await page.click('[data-tab="audio"]');await page.locator('[data-post="3"]').waitFor();await page.click('[data-post="3"]');if(!(await page.locator('[data-media]').count()))throw Error('Audio link missing');
 await page.click('[data-action="back"]');await page.click('[data-nav="explore"]');await page.fill('#query','stories');await page.locator('#searchForm button').click();await page.locator('[data-post="1"]').waitFor();
 await page.reload();await page.locator('[data-post="1"]').waitFor();await page.click('[data-nav="saved"]');await page.locator('[data-post="1"]').waitFor();offline=true;
 await page.reload();await page.click('[data-nav="saved"]');await page.locator('[data-post="1"]').waitFor();await page.click('[data-post="1"]');await page.locator('.article').waitFor();
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Horizontal overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: reading, sanitation, saving, favorites, persistence, offline saved text, theme, category/tag media filtering, audio link, search, mobile overflow.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
